### ISSUE TITLE
Feature Request [Channel Binding] (100% complete)

### ISSUE THREAD

**Issue by snaildos** [kt5company/discord-uptimerobot#2]
Bind the bot to a specific channel and update the embeds every 5 mins to show if a service is online or not.
:)

**Comment by ktg5** [comment]
Workin' on this right now -- it'll be out as soon as possible (as with a Discord.JS update to v12 because why not).

**Comment by ShadowElysium** [comment]
Excited about this :D

**Comment by ktg5** [comment]
I want to give an update on this feature update.

Yes -- I am working on it; I've been too focused in school and live streaming which resulted in not working on this update.

I'd like to apologize for my lazy ass taking so long to get this out. Hopefully it will be done soon.

**Comment by ktg5** [comment]
I can now officially say that this feature is now complete and a new push will be out soon.

**Comment by snaildos** [comment]
Thank you, this is amazing, It's just I don't know what to put in for the monitor ID?

**Comment by snaildos** [comment]
I got the ID, but instead I got
 (node:25) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at /home/container/commands/service.js:31:66
    at /home/container/node_modules/promise/lib/core.js:33:15
    at flush (/home/container/node_modules/asap/asap.js:27:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:25) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ktg5** [comment]
Send the line of code that's causing the issue.

**Comment by snaildos** [comment]
@ktg5 {
  "monitors": [
    {
      "name": "cluster1",
      "value": "787378295"
    }
  ]
}

**Comment by ktg5** [comment]
the only thing i would really say is if the args in `monitorlist` is set as `1` for the first one, you actually need to set it as `0` instead.

**Comment by snaildos** [comment]
What monitorlist?

**Comment by snaildos** [comment]
var monitor = botTools.findMonitor(res, monitorlist[1].value); ?

**Comment by snaildos** [comment]
Ok, I got it. It does not send to the channel tho and does not update?

**Comment by ktg5** [comment]
You should have defined the guild ID and channel ID in the `info.json` file, or else the the bot will not send the message(s) to the specific channel. And what do you mean by "does not update"?

**Comment by snaildos** [comment]
Huh? Doesn't it send a status thing and update the message by editing it?

**Comment by ktg5** [comment]
I might have forgot about the editing part...

**Comment by snaildos** [comment]
Oh-

**Comment by snaildos** [comment]
Also it keeps spamming (node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:36) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at Timeout._onTimeout (/home/container/bot.js:74:49)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:36) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at Timeout._onTimeout (/home/container/bot.js:74:49)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:36) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channels' of undefined
    at Timeout._onTimeout (/home/container/bot.js:74:49)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
(node:36) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Comment by ktg5** [comment]
Send the line of code from `bot.js` line 74.

**Comment by snaildos** [comment]
// Find commands (/commands folder)
fs.readdir("./commands/", (err, files) => {
    if(err) console.log(err);

    let jsfile = files.filter(f => f.split(".").pop() === "js")
    if(jsfile.length <= 0){
        logger.warn("Couldn't find commands.");
        return;
    }

**Comment by ktg5** [comment]
1. Check to see if you gave the bot the correct IDs.
2. Make sure the bot has permission to read and write to the channel.

Also make sure that line 68 is running async commands (aka `setInterval(async () => {`)

**Comment by ktg5** [comment]
Also in the future I'll make it so the bot will just delete the past messages, because editing past multiple messages would seem difficult.

**Comment by snaildos** [comment]
I'm confused. It still does not work. It has correct id, and has admin permission.

**Comment by snaildos** [comment]
```{
    "ver": "2.0",
    "build-number": "1062",
    "build-name": "Version 2.0",
    
    "CMDS": true,

    "ownerID": "501691742064476161",
    
    "prefix": "stat!",

    "guild": 522708457963388948,
    "channel": 686720369821745303
}```

**Comment by ktg5** [comment]
The only thing I would suggest is replacing the `bot.js` file from your bot with the latest `bot.js` file from this repo. Or just restart from this repo again.

**Comment by snaildos** [comment]
Hello, I got it all too work now, except still the sending bit. 
![image](https://user-images.githubusercontent.com/46210117/118644314-43b73600-b810-11eb-87fe-6c80608fe67a.png)
Idk why I am getting this, but all the status works perfectly now.

**Comment by ktg5** [comment]
I actually just remembered something and it might be the reason why you are having this issue.

In your `info.json`, you must put quotes around the ID since it's too long and the last 2 numbers will be zeros.

This should fix the issue as I remember this happening when I was testing this at first.

**Comment by snaildos** [comment]
Can confirm it works. You are epic. Thank you so much for this. ^w^

**Comment by ktg5** [comment]
Next time when it comes to trying to get help with the bot itself, [please join our support server](https://discord.gg/8QTX46D)
